import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4'])
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/component/shered/Navber";
import 'animate.css';

import Footer from "@/component/shered/Footer";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
      suppressHydrationWarning
      className="min-h-full flex flex-col">
        <ToastContainer />
        <Navber></Navber>
        <main>
        {children}
        </main>
        <Footer></Footer>
        
        
        
        
        </body>
    </html>
  );
}
